import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
import joblib

# 1️⃣ Set paths
FEATURES_CSV = "features.csv"  # CSV generated by extract_features.py
MODEL_FILE = "model.joblib"
LABEL_ENCODER_FILE = "label_encoder.joblib"

# 2️⃣ Load features
if not os.path.exists(FEATURES_CSV):
    raise FileNotFoundError(f"{FEATURES_CSV} not found. Run extract_features.py first.")

df = pd.read_csv(FEATURES_CSV)
print(f"✅ Loaded {len(df)} samples from {FEATURES_CSV}")

# 3️⃣ Split features and labels
X = df.drop("label", axis=1)
y = df["label"]

# 4️⃣ Encode labels
le = LabelEncoder()
y_encoded = le.fit_transform(y)
print(f"✅ Found genres: {list(le.classes_)}")

# 5️⃣ Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

# 6️⃣ Train classifier
model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)
print("✅ Model training completed")

# 7️⃣ Evaluate accuracy
accuracy = model.score(X_test, y_test)
print(f"🎯 Test accuracy: {accuracy*100:.2f}%")

# 8️⃣ Save model and label encoder
joblib.dump(model, MODEL_FILE)
joblib.dump(le, LABEL_ENCODER_FILE)
print(f"💾 Model saved to {MODEL_FILE}")
print(f"💾 Label encoder saved to {LABEL_ENCODER_FILE}")
